title: Mohammed Mudarris
description: PhD Candidate – Leiden University
theme: jekyll-theme-minimal

logo: /Self_portrait.JPG

header_pages:
  - research.md
  - publications.md
  - presentations.md
  - cv.md
  - contact.md
