project:
  type: website
  output-dir: docs

website:
  title: "Mohammed Mudarris"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: presentations.qmd
        text: Presentations
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    toc: true
