# Mohammed Mudarris

PhD Candidate  
Health, Medical, Neuropsychology
Institute of Psychology  
Faculty of Social and Behavioural Sciences
Leiden University

PhD candidate in Health-Medical Neuropsychology at Leiden University. Clinical Neuropsychology, MSc (cum laude; Leiden University). Biopsychology, B.S. (University of California–Santa Barbara). 

Research focuses on neuroplasticity of motor-learning with multisensory stimulation in aging and disease. Using multimodal MRI methods to reveal structural, functional and network brain changes, as well as standardized measures of cognitive, motor and psychological functioning before and after motor learning with multi-sensory (audiovisual) stimulation.

Clinically trained in neuropsychological evaluation of Epilepsy, acquired brain injuries, neurodegenerative (Parkinson’s Disease, Dementia), neurodevelopmental (Autism, ADHD), neuropsychiatric, genetic and rare conditions. Contributed to clinical management of candidates for neurosurgery, with experience in Wada test and functional cortical mapping. 

Formerly, an administrative manager in multidisciplinary mental health care. 
## Research Interests

- Neuroimaging
- Motor learning & cognition
- Aging and stroke
- Music-based rehabilitation
- Multisensory stimulation
- Cognitive-motor interference
- Hierarchical modelling

## Pages

- [Research](research)
- [Publications](publications)
- [Presentations](presentations)
- [CV](cv)
- [Contact](contact)
