---
title: "Presentations"
---

## Invited Talks

**Audiovisual stimulation of motor learning: A longitudinal multimodal MRI study**  
Center for Cognitive and Behavioral Brain Imaging, Ohio State University — Cincinnati, USA  
Nov 2023

**Neuropsychological Assessment of Psychosomatic Disorders**  
Psychosomatic Review Course, King Abdullah Medical City — Makkah, Saudi Arabia  
Oct 2023

---

## Conference Talks

### 2025
**Grey matter changes following music-cued visuomotor learning in older adults**  
**Mudarris, M. A.**, Ruwe, O., Rombouts, S. A. R. B., Veldhuijzen, D. S., & Schaefer, R. S.  
International Neuropsychological Society / Australian Society for the Study of Brain Impairment — Brisbane, Australia  
Jul 2025

### 2024
**Cortical grey matter changes related to music-cued motor sequence learning**  
**Mudarris, M. A.**, Besemer, E. S., Moore, E., Roberts, N., Veldhuijzen, D. S., Rombouts, S. A. R. B., Overy, K., & Schaefer, R. S.  
LUMC Neuroscience Symposium — Leiden, Netherlands  
Oct 2024

### 2022
**Perceptually embedded motor learning with multimodal cues**  
Schaefer, R. S., Hamilton, A., **Mudarris, M. A.**[^1], Ruitenberg, M. F. L.  
Dutch Society for Brain & Cognition Conference — Egmond aan Zee, Netherlands  
Apr 2022  

[^1]: presenting author

### 2021
**Examining exerted force in a music-cued finger tapping task: A multilevel approach**  
**Mudarris, M. A.**, & Schaefer, R. S.  
International Motor Impairment Conference — Amsterdam, Netherlands  
Nov 2021

---

## Conference Posters

### 2025
**Cortical grey matter changes following a 4-week auditory-cued visuomotor training**  
**Mudarris, M. A.**, Moore, E., Roberts, N., Bastin, M. E., Veldhuijzen, D. S., Rombouts, S. A. R. B., Overy, K., & Schaefer, R. S.  
Organization for Human Brain Mapping — Brisbane, Australia  
Jun 2025

### 2024
**Structural changes in cortical grey matter related to auditory-motor sequence training**  
**Mudarris, M. A.**, Besemer, E. S., Roberts, N., Overy, K., & Schaefer, R. S.  
Neuroscience of Music VIII — Helsinki, Finland  
Jun 2024

### 2023
**The role of cognitive-motor interference in rhythmic auditory stimulation**  
**Mudarris, M. A.**, & Schaefer, R. S.  
ICMPC17 / APSCOM7 — Tokyo, Japan  
Aug 2023

### 2022
**Musical training may not enhance cognitive-motor integration in healthy young adults**  
**Mudarris, M.**, & Schaefer, R.  
Journal of the International Neuropsychological Society — San Diego, USA  
Feb 2022

### 2021
**Dissociations between familiarity and preference ratings of music for healthy young and older adults**  
**Mudarris, M. A.**, & Schaefer, R. S.  
ICMPC16 / ESCOM11 — Sheffield, UK  
Jul 2021

**Predictors of exerted force in a music-cued sensorimotor synchronization task**  
**Mudarris, M. A.**, & Schaefer, R. S.  
Neuroscience of Music VII — Aarhus, Denmark  
Jun 2021
