---
title: Publications
---

# Peer-Reviewed Publications

**Cognitive and motor abilities predict auditory-cued finger tapping in a dual task**  
**Mudarris, M. A.**, Krijt, R. N., Hassell, A. M., Murphy, T. M., Ruitenberg, M. F. L., Fokkema, M., & Schaefer, R. S. (2025)  
*Frontiers in Neuroscience*, 19:1553548  
[https://doi.org/10.3389/fnins.2025.1553548](https://doi.org/10.3389/fnins.2025.1553548) · [OSF](https://osf.io/pfhn3)

---

**Music therapy with adults in the subacute phase after stroke: A study protocol**  
Dimitriadis, T., **Mudarris, M. A.**[^1], Veldhuijzen, D. S., Evers, A. W. M., Magee, W. L., & Schaefer, R. S. (2024)  
*Contemporary Clinical Trials Communications*, 41, 101340  
[https://doi.org/10.1016/j.conctc.2024.101340](https://doi.org/10.1016/j.conctc.2024.101340)


---

**Feasibility study of the Boston Naming Test for the Arab population**  
Basura, H. A., **Mudarris, M.**, Almubarak, F. B., Alzahrani, S. A., Alghamdi, H., Alsulami, A., Alnakhli, A., Alzahrani, G., & Tayeb, H. O. (2024)  
*Cureus*, 16(1)  
[https://doi.org/10.7759/cureus.52351](https://doi.org/10.7759/cureus.52351)

**Category-specific fMRI correlates of picture naming: A study with Arabs and Filipinos**  
Tayeb, H. O., Alghamdi, J., Ahmed, N., Alsawwaf, Y., Alsafi, K., Baduwailan, A., Yaghmoor, B., Elyas, T., **Mudarris, M.**, & Weisholtz, D. S. (2022)  
*Journal of Neurolinguistics*, 63, 101065  
[https://doi.org/10.1016/j.jneuroling.2022.101065](https://doi.org/10.1016/j.jneuroling.2022.101065)

[^1]: Shared first authorship

---

# Preprints and Manuscripts Under Review

**Introducing the INSConnect Survey: A tool for mapping global neuropsychological assessment practices**  
Dobson, L., Brandon, F., Porrselvi, A. P., Casey, V., Doyle, A. E., Kramska, L., **Mudarris, M. A.**, Fonseca, R. P., Pender, N., Schrieff-Brown, L., Talbert, L. D., WINDS, Jenkins, L. M.  
*Manuscript under review*

---

**Increased surface area of Heschl’s gyrus following music-cued motor training**  
**Mudarris, M. A.**, Moore, E., Roberts, N., Bastin, M. E., Veldhuijzen, D. S., Rombouts, S. A. R. B., Overy, K., & Schaefer, R. S. (2025)  
bioRxiv  
[Preprint](https://doi.org/10.1101/2025.10.09.675791) · [OSF](https://osf.io/hwdb8)  
*Manuscript under review*


---

**Tap Harder: Cognitive inhibition and induced emotions predict tapping force in young and older adults**  
**Mudarris, M. A.**, & Schaefer, R. S. (2025)  
PsyArXiv  
[Preprint](https://doi.org/10.31234/osf.io/hjdpr_v2) · [OSF](https://osf.io/tx5cg)  
*Manuscript under review*

---

**Enhancing motivation through music therapy in subacute stroke rehabilitation: a within-subject crossover study**  
Dimitriadis, T., Huisman, S., **Mudarris, M. A.**, Veldhuijzen, D. S., Evers, A., Magee, W., & Schaefer, R. S. (2025)  
OSF Preprints  
[Preprint](https://doi.org/10.31219/osf.io/4va6n)  
*Manuscript under review*

---

# Manuscripts in Preparation

**Structural and functional connectivity following audiovisual motor learning in older adults**  
**Mudarris, M. A.**, Hall, J. M., Ruwe, O., Veldhuijzen, D. S., Rombouts, S. A. R. B., & Schaefer, R. S.

---

**Are two senses better than one? A systematic review showing advantages of multisensory stimulation for motor learning**  
**Mudarris, M. A.**, Ruitenberg, M. F. L., Petratza, M. M., Murphy, T. M., Pérez, S. A., Dimitriadis, T., Schoones, J. W., & Schaefer, R. S.
